#! /usr/bin/env bash
repo_dir=$HOME/.vim/pack/git-plugins
silent=false


####
# This handles the optional arguments
###

SHORT=sd:
LONG=silent,git-dir:
getopt --test > /dev/null
if (( $? == 4 )); then
	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
else
	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
fi

if (( $? != 0 )); then
	echo "Failed to parse arguments"
	exit 2
fi

eval set -- "$PARSED"
while true; do
	case "$1" in
		-d|--git-dir)
			repo_dir=$2
			shift 2
			;;
		-s|--silent)
			silent=true
			shift
			;;
		--)
			shift
			break
			;;
		*)
			shift
			;;
	esac
done

start_opt=$1
repo_target=$2
dest_name=$3

echo "$start_opt"
echo "$repo_target"
echo "$dest_name"

cd "$repo_dir/$start_opt"
if [[ "$silent" == true ]]; then
	git clone "$repo_target" "$dest_name" > /dev/null
else
	git clone "$repo_target" "$dest_name"
fi

exit $?
