#! /usr/bin/env bash

COMMAND=$1
shift

echo "Command: $COMMAND"
if [ "$COMMAND" == "update" ]; then
	vim-pack-update "$@"
elif [ "$COMMAND" == "upgrade" ]; then
	vim-pack-upgrade "$@"
elif [ "$COMMAND" == "get"  ] || [ "$COMMAND" == "install"  ]; then
	vim-pack-get "$@"
elif [ "$COMMAND" == "install"  ]; then
	vim-pack-get "$@"
elif [ "$COMMAND" == "remove"  ]; then
	vim-pack-remove "$@"
elif [ "$COMMAND" == "export"  ] || [ "$COMMAND" == "list"  ]; then
	vim-pack-export "$@"
elif [ "$COMMAND" == "import"  ]; then
	vim-pack-import "$@"
else
	echo "usage: vim-pack <command> [<args>]"
	echo
	echo "Comands:"
	echo "    get        Used to download a package from a git based source"
	echo "    install    Used to download a package from a git based source"
	echo "    list       List installed packages"
	echo "    remove     Used to remove a package"
	echo "    update     Used to find all the packages that have updates"
	echo "    upgrade    Used to update all the packages"
	echo "    import     Import package list"
	echo "    export     Export a package list"
	exit 1
fi
exit $?
