#! /usr/bin/env bash
my_dir="$(dirname $(readlink "$0"))"
source "$my_dir/bash_ini_parser/read_ini.sh"
repo_dir=$HOME/.vim/pack/git-plugins
silent=false


####
# This handles the optional arguments
###
getopt --test > /dev/null
if [[ $? -ne 4 ]]; then
    echo "$(getopt --test) failed in this environment."
    exit 1
fi

SHORT=sd:
LONG=silent,git-dir:
PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")

if [[ $? -ne 0 ]]; then
		echo "Failed to parse arguments"
    exit 2
fi

eval set -- "$PARSED"
while true; do
	case "$1" in 
		-d|--git-dir)
			repo_dir=$2
			shift 2
			;;
		-s|--silent)
			silent=true
			shift
			;;
		--)
			shift
			break
			;;
		*)
			break
			;;
	esac
done

import_file=$1
read_ini $import_file

for sec in ${INI__ALL_SECTIONS}; do
	v="INI__${sec}__url"
	repo_target=${!v}
	v="INI__${sec}__dir"
	dest_name=${!v}
	if [ "$silent" = true ]; then 
		git clone $repo_target $repo_dir/$dest_name > /dev/null
	else
		git clone $repo_target $repo_dir/$dest_name
	fi
done

exit $?
