#! /usr/bin/env bash
repo_dir=$HOME/.vim/pack/git-plugins
silent=false

####
# This handles the optional arguments
###
SHORT=sd:o:
LONG=silent,git-dir:,output:
getopt --test > /dev/null
if (( $? == 4 )); then
	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
else
	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
fi

if (( $? != 0 )); then
	echo 'Failed to parse arguments'
	exit 2
fi

eval set -- "$PARSED"
while true; do
	case "$1" in
		-d|--git-dir)
			repo_dir=$2
			shift 2
			;;
		-s|--silent)
			silent=true
			shift
			;;
		--)
			shift
			break
			;;
		*)
			echo "Unknown argument: " "$1"
			exit 3
			;;
	esac
done

if [[ "$silent" == true ]]; then
	for i in {opt,start}; do
		for j in $repo_dir/$i/*/; do
			git -C "$j" pull > /dev/null
		done
	done
else
	for i in {opt,start}; do
		for j in $repo_dir/$i/*; do
			echo "$j"
			git -C "$j" pull
		done
	done
fi

exit 0
