#! /bin/bash
repo_dir=$HOME/.vim/pack/git-plugins
silent=false


####
# This handles the optional arguments
###
getopt --test > /dev/null
if [[ $? -ne 4 ]]; then
    echo "$(getopt --test) failed in this environment."
    exit 1
fi

SHORT=sd
LONG=silent,git-dir:
PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")

if [[ $? -ne 0 ]]; then
		echo "Failed to parse arguments"
    exit 2
fi

eval set -- "$PARSED"
while true; do
	case "$1" in 
		-d|--git-dir)
			repo_dir=$2
			shift 2
			;;
		-s|--silent)
			silent=true
			shift
			;;
		--)
			shift
			break
			;;
		*)
			shift
			;;
	esac
done

if [[ $# -eq 2 ]]; then
	start_opt=$1
	pack_name=$2
	if [ "$silent" = true ]; then 
		rm -rf "$repo_dir/$start_opt/$pack_name" > /dev/null
	else
		rm -rf "$repo_dir/$start_opt/$pack_name"
	fi
elif [[ $# -eq 1 ]]; then
	pack_name=$1
	if [ "$silent" = true ]; then 
		rm -rf "$repo_dir/start/$pack_name" > /dev/null
		rm -rf "$repo_dir/opt/$pack_name" > /dev/null
	else
		rm -rf "$repo_dir/start/$pack_name"
		rm -rf "$repo_dir/opt/$pack_name"
	fi
fi


exit $?
